### ISSUE TITLE
Add more passwords

### ISSUE THREAD

**Issue by arch-user-france1** [Explodingstuff/paswwords-list#3]
lol

**Comment by cheng-alvin** [comment]
lol

**Comment by ui0ppk** [comment]
password123

**Comment by cheng-alvin** [comment]
![TheComputerForgotMyPasswordPasswordGIF](https://github.com/Explodingstuff/paswwords-list/assets/88267875/746f9c30-d774-402b-a6a4-4f8011a98c8b)

**Comment by molangning** [comment]
why is this repository blacklisted on github robots.txt?

**Comment by arch-user-france1** [comment]
<img width="415" alt="image" src="https://github.com/Explodingstuff/paswwords-list/assets/72965843/12d941ad-9b8f-48e3-bb73-0aeaefcbd476">
I have no idea.
